FROM ubuntu:20.04 as builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install build-essential pbuilder aptitude git openssh-client ca-certificates

RUN git clone --branch=v0.18.0 --depth=1 https://github.com/iovisor/bcc.git /root/bcc && \
    git -C /root/bcc submodule update --init --recursive

RUN cd /root/bcc && \
    /usr/lib/pbuilder/pbuilder-satisfydepends && \
    PARALLEL=$(nproc) ./scripts/build-deb.sh release

FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential software-properties-common

COPY --from=builder /root/bcc/libbcc_*.deb /tmp/libbcc.deb

RUN dpkg -i /tmp/libbcc.deb

RUN apt-get install --assume-yes --force-yes python  python3-pip
RUN apt-get install --assume-yes --force-yes bpfcc-tools linux-headers-$(uname -r)
RUN pip install prometheus_client
RUN mkdir prometheus_exporter
COPY library/ prometheus_exporter/library/
COPY script/ prometheus_exporter/script/
WORKDIR prometheus_exporter/script
RUN chmod +x ./run.sh
ENTRYPOINT [ "./run.sh"]
