FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install --assume-yes --force-yes python  python3-pip
RUN apt-get install --assume-yes --force-yes bpfcc-tools linux-headers-$(uname -r)
RUN pip install prometheus_client
WORKDIR /prometheus_exporter
COPY ../library /prometheus_exporter
COPY ../script /prometheus_exporter

ENTRYPOINT [ "./run.sh"]
